In [3]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [4]:
url = 'https://developer.taiyo.ai/api-doc/TimeSeries/'
req = requests.get(url)
print(req) #To verify output

<Response [200]>

In [5]:
soup = BeautifulSoup(req.content, 'html.parser')
#print(soup) #To verify output (VERY LONG)

In [6]:
tabela = soup.find(name='table')
#print(tabela) #To verify output (VERY LONG)

In [7]:
print(tabela)

<table>
<thead>
<tr>
<th>Primary Fields</th>
<th>Description</th>
<th>Notes</th>
<th>Additional Comments</th>
</tr>
</thead>
<tbody>
<tr>
<td>Identifier</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>aug_id</td>
<td>ID generated for unique identification</td>
<td>This resembles {source}_{original_id}</td>
<td></td>
</tr>
<tr>
<td>original_id</td>
<td>ID originally provided by the data source</td>
<td></td>
<td>If this ID is not present it is to be generated from the asset name or title</td>
</tr>
<tr>
<td>sample_frequency</td>
<td>sample frequency of the time_series</td>
<td>Valid Values or Daily, Weekly, Monthly, Quaterly</td>
<td></td>
</tr>
<tr>
<td>Basic Specs</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>name</td>
<td>Name or Title of the time series</td>
<td></td>
<td></td>
</tr>
<tr>
<td>description</td>
<td>Any descriptive information present about the timeseries</td>
<td>Can come from basic description or abstract or development objective. The source may use different synonyms for description</td>
<td>We may also keep the similar sounding fields as secondary fields where description if present becomes primary one</td>
</tr>
<tr>
<td>units</td>
<td>the units of measurement of the timeseries</td>
<td></td>
<td></td>
</tr>
<tr>
<td>source</td>
<td>Source Abbr.</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Links and URLs</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>url</td>
<td>Link to the microsite of the timeseries</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Sector/Subsector or Industry Type</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>domain</td>
<td>domain of the data source</td>
<td></td>
<td></td>
</tr>
<tr>
<td>subdomain</td>
<td>subdomain of the data source</td>
<td></td>
<td></td>
</tr>
<tr>
<td>tags</td>
<td>Important keywords identified from overall textual content present about the asset</td>
<td>Includes both tags for sector and subsector and some other technical keywords</td>
<td></td>
</tr>
<tr>
<td>Critical Dates</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>timestamps</td>
<td>start date, end date of the timeseries as a dictionary type</td>
<td></td>
<td></td>
</tr>
<tr>
<td>Location Information</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>country_name</td>
<td>The short country name</td>
<td></td>
<td></td>
</tr>
<tr>
<td>country_code</td>
<td>ISO 3166-1 alpha-3 country codes</td>
<td>Should not be the official name For eg: Republic of India (this should be converted to India)</td>
<td></td>
</tr>
<tr>
<td>region_name</td>
<td></td>
<td>According to standards followed by WorldBank</td>
<td></td>
</tr>
<tr>
<td>region_code</td>
<td>3 ISO format</td>
<td>3 digit region codes followed by World Bank</td>
<td></td>
</tr>
<tr>
<td>location</td>
<td>The exact or approx. location</td>
<td>May or may not be given by the source</td>
<td></td>
</tr>
<tr>
<td>map_coordinates</td>
<td>Geographical Coordinates in decimal degree system</td>
<td>[ [ latitude, longitude ], ... ] or [] if None</td>
<td>If only map coordinates are given then these can reverse geocoded upto city level</td>
</tr>
<tr>
<td>state</td>
<td>State Name</td>
<td>Generated after geocoding</td>
<td></td>
</tr>
<tr>
<td>county</td>
<td>County/District Name</td>
<td>Generated after geocoding</td>
<td></td>
</tr>
<tr>
<td>city</td>
<td>City Name</td>
<td>Generated after geocoding</td>
<td></td>
</tr>
<tr>
<td>locality</td>
<td>Nearest locality</td>
<td>Generated after geocoding</td>
<td></td>
</tr>
<tr>
<td>nieghbourhood</td>
<td></td>
<td>Generated after geocoding. It may or may not get identified</td>
<td></td>
</tr>
</tbody>
</table>

In [8]:
df = pd.concat(pd.read_html('https://developer.taiyo.ai/api-doc/TimeSeries/'),axis=1)

In [9]:
df.head(5)

,Primary Fields,Description,Notes,Additional Comments
0,Identifier,NaN,NaN,NaN
1,aug_id,ID generated for unique identification,This resembles {source}_{original_id},NaN
2,original_id,ID originally provided by the data source,NaN,If this ID is not present it is to be generate...
3,sample_frequency,sample frequency of the time_series,"Valid Values or Daily, Weekly, Monthly, Quaterly",NaN
4,Basic Specs,NaN,NaN,NaN

In [10]:

# saving the dataframe
df.to_csv('file1.csv')